services:
  - type: web
    name: visual-quiz-game
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT quiz_game.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: quiz_game.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: visual-quiz-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: visual-quiz-redis
          type: redis
          property: connectionString

databases:
  - name: visual-quiz-db
    databaseName: visualquiz
    plan: free

  - name: visual-quiz-redis
    type: redis
    plan: free
